---
abstract: 'Pegex CSV Parser/Loader'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  YAML::XS: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pegex-CSV
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  Pegex: '0'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/pegex-csv-pm/issues
  homepage: https://github.com/ingydotnet/pegex-csv-pm
  repository: https://github.com/ingydotnet/pegex-csv-pm.git
version: 0.0.3
